"""Plain text export functionality."""

from datetime import datetime
from pathlib import Path

from dnsviz_tui.models.chain import TrustChain, ZoneInfo, ValidationStatus


def _format_header(chain: TrustChain) -> str:
    """Format the header section."""
    lines = [
        "=" * 70,
        f"DNSSEC Chain of Trust Analysis",
        "=" * 70,
        "",
        f"Domain:        {chain.target_domain}",
        f"Query Time:    {chain.query_time.strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"Query Duration: {chain.query_duration_ms:.2f}ms",
        f"Resolver:      {chain.resolver_used}",
        "",
        f"Overall Status: {chain.overall_status.symbol} {chain.overall_status.value.upper()}",
        f"Reason:        {chain.overall_reason}",
        "",
        f"Chain Path:    {' -> '.join(chain.chain_path())}",
        "",
    ]
    return "\n".join(lines)


def _format_zone(zone: ZoneInfo) -> str:
    """Format a zone section."""
    lines = [
        "-" * 70,
        f"Zone: {zone.name}",
        "-" * 70,
        f"Status: {zone.status.symbol} {zone.status.value.upper()}",
    ]

    if zone.status_reason:
        lines.append(f"Reason: {zone.status_reason}")

    if zone.parent:
        lines.append(f"Parent: {zone.parent}")

    lines.append("")

    # DNSKEY records
    if zone.dnskeys:
        lines.append("DNSKEY Records:")
        for key in zone.dnskeys:
            key_type = "KSK" if key.is_ksk else "ZSK"
            lines.append(
                f"  [{key_type}] Tag: {key.key_tag}, "
                f"Algorithm: {key.algorithm_name}, "
                f"Bits: {key.key_length}"
            )
        lines.append("")

    # DS records
    if zone.ds_records:
        lines.append("DS Records:")
        for ds in zone.ds_records:
            validates = f" -> validates {ds.validates_key}" if ds.validates_key else ""
            lines.append(
                f"  Tag: {ds.key_tag}, "
                f"Algorithm: {ds.algorithm_name}, "
                f"Digest: {ds.digest_type_name}{validates}"
            )
        lines.append("")

    # RRSIG records
    if zone.rrsigs:
        lines.append("RRSIG Records:")
        for rrsig in zone.rrsigs:
            status = "EXPIRED" if rrsig.is_expired else f"valid {rrsig.days_until_expiry}d"
            lines.append(
                f"  Covers: {rrsig.type_covered}, "
                f"Key: {rrsig.key_tag}, "
                f"Expires: {rrsig.expiration.strftime('%Y-%m-%d')} ({status})"
            )
        lines.append("")

    # Additional records
    if zone.additional_records:
        lines.append("Additional Records:")
        for rec in zone.additional_records:
            signed = " [SIGNED]" if rec.is_signed else ""
            value = rec.value
            if len(value) > 50:
                value = value[:47] + "..."
            lines.append(f"  {rec.record_type}: {value}{signed}")
        lines.append("")

    # Validation summary
    lines.append("Validation:")
    lines.append(f"  DS Validated:     {'Yes' if zone.ds_validated else 'No'}")
    lines.append(f"  DNSKEY Validated: {'Yes' if zone.dnskey_validated else 'No'}")
    lines.append(f"  Chain Complete:   {'Yes' if zone.chain_complete else 'No'}")
    lines.append("")

    return "\n".join(lines)


def _format_summary(chain: TrustChain) -> str:
    """Format the summary section."""
    lines = [
        "=" * 70,
        "SUMMARY",
        "=" * 70,
        "",
        f"{'Zone':<25} {'Status':<12} {'Keys':<8} {'DS->DNSKEY':<12} {'Chain'}",
        "-" * 70,
    ]

    for zone in chain.zones:
        name = zone.name if len(zone.name) <= 24 else zone.name[:21] + "..."
        status = f"{zone.status.symbol} {zone.status.value}"
        keys = f"{zone.ksk_count}K/{zone.zsk_count}Z" if zone.dnskeys else "-"
        ds_val = "Anchor" if zone.name == "." else ("Yes" if zone.ds_validated else "No")
        chain_ok = "Yes" if zone.chain_complete else "No"

        lines.append(f"{name:<25} {status:<12} {keys:<8} {ds_val:<12} {chain_ok}")

    lines.append("")
    lines.append("=" * 70)
    lines.append(f"Generated by dnsviz-tui at {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append("=" * 70)

    return "\n".join(lines)


def export_text(chain: TrustChain, path: Path | str | None = None) -> str:
    """Export trust chain to plain text.

    Args:
        chain: The trust chain to export
        path: Optional file path to write to

    Returns:
        Plain text string
    """
    sections = [_format_header(chain)]

    for zone in chain.zones:
        sections.append(_format_zone(zone))

    sections.append(_format_summary(chain))

    text = "\n".join(sections)

    if path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    return text
